<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Home Formulário Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'painter@adobe.com',
		'to' => 'painter@adobe.com'
	),
	'fields' => array(
		'custom_U1613' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome completo',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nome completo\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U1592' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Endereço',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Endereço\' is required.'
			)
		),
		'custom_U1622' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'CPF',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'CPF\' is required.'
			)
		),
		'custom_U1618' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'RG',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'RG\' is required.'
			)
		),
		'custom_U1605' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Nome da mãe',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nome da mãe\' is required.'
			)
		),
		'custom_U1627' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Data de nascimento',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Data de nascimento\' is required.'
			)
		),
		'custom_U1631' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Telefone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Telefone\' is required.'
			)
		),
		'custom_U1596' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Modelo do carro (opicional)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Modelo do carro (opicional)\' is required.'
			)
		),
		'custom_U1609' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Valor do carro',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
