<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Home Formulário envio',
	'heading' => 'Envio de novo formulário',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcado',
		'checkbox_unchecked' => 'Desmarcado',
		'submitted_from' => 'Formulário enviado do site: %s',
		'submitted_by' => 'Endereço IP do visitante: %s',
		'too_many_submissions' => 'Muitos envios recentes deste IP',
		'failed_to_send_email' => 'Falha no envio do email',
		'invalid_reCAPTCHA_private_key' => 'Chave privada do reCAPTCHA inválida.',
		'invalid_reCAPTCHA2_private_key' => 'Chave privada do reCAPTCHA 2.0 inválida.',
		'invalid_reCAPTCHA2_server_response' => 'Resposta do servidor reCAPTCHA 2.0 inválida.',
		'invalid_field_type' => 'Tipo de campo desconhecido \"%s\".',
		'invalid_form_config' => 'O campo \"%s\" possui uma configuração inválida.',
		'unknown_method' => 'Método de solicitação de servidor desconhecido'
	),
	'email' => array(
		'from' => 'franciscosovinski@hotmail.com',
		'to' => 'franciscosovinski@hotmail.com'
	),
	'fields' => array(
		'custom_U946' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome completo',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Nome completo\" é obrigatório.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Email\" é obrigatório.',
				'format' => 'O campo \"Email\" possui um email inválido.'
			)
		),
		'custom_U918' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Endereço',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Endereço\" é obrigatório.'
			)
		),
		'custom_U954' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'CPF',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"CPF\" é obrigatório.'
			)
		),
		'custom_U927' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'RG',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"RG\" é obrigatório.'
			)
		),
		'custom_U942' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Data de nascimento',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Data de nascimento\" é obrigatório.'
			)
		),
		'custom_U932' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Nome da mãe',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Nome da mãe\" é obrigatório.'
			)
		),
		'custom_U938' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Telefone',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Telefone\" é obrigatório.'
			)
		),
		'custom_U1190' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Valor do carro',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Valor do carro\" é obrigatório.'
			)
		),
		'custom_U1202' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Modelo do carro (opcional)',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
